version: '3.8'

services:
  web:
    build: .
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=portfolio.settings
    restart: unless-stopped
